### ISSUE TITLE
Ship Theming UI & Foundation

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10251]
**Goal:** Complete Foundation theme so it can be shipped to allow customers to start using it and provide feedback. 

## Tasks

- [ ] Symlink and enable theme UI on infrastructure in the default server config.
- [ ] Mark the the theme UI addon as hidden.
- [ ] Spawn new sites with Foundation. Default all new customer sites to use Foundation.
- [ ] Write a jobber to make sure everyone has a current theme.
- [ ] Disable customize theme when the theme UI is enabled.
- [ ] Mark old themes as hidden (everything except Keystone and Foundation).
- [ ] QA.

## Notes

- When Foundation theme is enabled, we'll need to hide the old theme page.
- All new customers should be using the new Theming UI
- If for some reason a customer needs to go back to the old theme.

## Acceptance Criteria

- Sites without a Foundation theme should still work.
- Sites with a customized theme using the customize theme should still be able to use that plugin.
- Add a "Looking for the old theme page?" link in the right panel to link to the old UI. Get wording from Todd.
- Sites with a separate mobile theme should continue to use that separate mobile theme.
   - If they set a new theme it will take over the mobile theme too. There should be some dialog.
- A new site should see Foundation as its theme and be able to copy/create a new theme.
- Stretch: If someone has a hidden theme enabled and then disables it it should still be allowed to show. Maybe add a config key for visible themes that will always display. Ask Alex C.
