### ISSUE TITLE
New Design for Events & Social Groups

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10378]
## Context
We will be doing some work to allow users to send group invites via email. We are also doing some work to leverage the Event's functionality in Social Groups to allow users to integrate events into their community categories. With this upcoming work in mind, we would like to start thinking about new designs for some of the key pages for event pages and eventually all social group pages. 

##  Design Tasks
Social Groups includes the pages below. They are listed here in order of priority regarding what 

- [x] Event Page - https://demo.vanillawip.com/en/event/1-lunch-and-learn
- [x] New Event Page - https://demo.vanillawip.com/en/event/add/2
- [x] Events List Page - https://demo.vanillawip.com/en/events/group/1-montreal-certification-group-august-2019
- [x] Upcoming Events Widget for Categories
- [x] Groups Homepage - https://demo.vanillawip.com/en/groups
- [x] Group Page - https://demo.vanillawip.com/en/group/1-montreal-certification-group-august-2019
- [x] Member Page - https://demo.vanillawip.com/en/group/members/1-montreal-certification-group-august-2019

**Comment by ElisaAlmeida** [comment]
It's all done. They are on Zeplin in the workspace Vanilla Forums (Group Page & Events):
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/dashboard?sid=5f0e0f22a4bc428d33c47719
