### ISSUE TITLE
Storybook v1

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9148]
## Buttons

* [x] Show code of buttons
* [x] Refactor functions into react components
* [x] display descriptions underneath (use when?)
* [x] Add example of button with icon

## Form Elements

* [x] Radiobuttons as tabs
* [x] text field
* [x] token field
* [x] dropdown field with search
* [x] date picker (group and not grouped)
* [x] checkbox
* [x] radio buttons
* [x] With and without labels

## Dropdowns

* [x] sections
* [x] meta
* [x] headings
* [x] Note that these will transform into modals on smaller screens. Document how that works.

## Search

* [x] self contained search
* [x] Title/meta/excerpt
* [x] Ellipsis menu button
* [x] Search results (show drafts and category as well)

## Modals

* [x] Do examples in mockup, with and without inputs

^ Most important ^

## Home page modules

* [x] Subcommunity chooser
* [x] List of links

## User Item

* [x] Variations on user item (from messages and from notifications)

## Headings

* [x] Show options of how you can have the look of h1 but using and h2 or any other combination

## Next/Prev

* [x] Add next/prev component

## Hero

* [x] List out options

## File Attachments

* [x] List out attachments
* [x] List out errors
