### ISSUE TITLE
Knowledge search within advanced search

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9318]
A user should be able to search knowledge along with the community within the community and advanced search and not just knowledge.

There were PRs for this functionality that we're rolled back. Can we get those dusted off and re-merged now that we have tests?

**Initial PRs**

- https://github.com/vanilla/internal/pull/1929
- https://github.com/vanilla/knowledge/pull/1106
- https://github.com/vanilla/knowledge/pull/1172 (revert PR)

**Acceptance Criteria**

- Any breaking changes to sphinx templates (if needed) should be updated in vanilla-docker & co-ordinated with ops for release.
  - _If a change improves UX but doesn't totally break the search, then this can take lower priority/happen in a future sprint._
- Accepts existing advanced search criteria: title, query, dateInserted, insertUser.
- Can query both KB articles and forum records together.
- Simple autocomplete working.
- When querying by forum category, no KB results should appear.
- Forum results are currently grouped by discussions, articles not should be included in these groupings.
- Integration tests harness

**Comment by alex-mtl** [comment]
- [ ] https://github.com/vanilla/vanilla/pull/9327
- [ ] https://github.com/vanilla/addons/pull/743
- [ ] https://github.com/vanilla/internal/pull/1986
