### ISSUE TITLE
Translation RESTful API polishing

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9615]
Let's make sure we use the right HTTP verbs and have symmetrical endpoints.

Let's have the following resources.

Hide `POST /translation`
Rename PUT -> `PATCH /translations`

`PATCH /translations/:resource/delete` 

## Tasks

- [x] Meet with Todd and Alex to go through the OpenAPI spec with all the endpoints we might want in the future.
- [x] Update existing endpoints to match the desired spec if necessary.
- [ ] **Stretch**. Implement sensible other endpoints so that we don't have to revisit this task in the future.

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/internal/pull/2089 and https://github.com/vanilla/internal/pull/2092
